services:
  backend:
    build:
      context: server
    command: npm run start:dev
    ports:
      - '5000:5000'
    volumes:
      - /usr/src/app/node_modules
      - ./server/src:/usr/src/app/src
    env_file:
      - server/.env

  frontend-dev:
    build: 
      context: ./client
      target: dev
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./client/src:/app/src
    env_file:
      - ./client/.env.local
    environment:
      - API_URL_SERVER=http://backend-dev:5008
    depends_on:
      - backend