name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      # CLIENT APP
      - name: Build and test client
        uses: docker/build-push-action@v6
        with:
          context: ./client
          target: test
          load: true
          
      - name: Build and push client
        uses: docker/build-push-action@v6
        with:
          context: ./client
          platforms: linux/amd64,linux/arm64
          push: true
          target: prod
          build-args: |
            NODE_VERSION=22-alpine
            NEXTAUTH_URL=${{secrets.NEXTAUTH_URL}}
            NEXT_PUBLIC_API_URL=${{secrets.NEXT_PUBLIC_API_URL}}
          tags: ${{ vars.DOCKER_USERNAME }}/codask-client
      
      #  SERVER APP
      - name: Build and push server
        uses: docker/build-push-action@v6
        with:
          context: ./server
          platforms: linux/amd64,linux/arm64
          push: true
          target: prod
          build-args: NODE_VERSION=22-alpine
          tags: ${{ vars.DOCKER_USERNAME }}/codask-server:latest
